# TODO: auth. with headers, with login:pass for dbs, etc
# TODO: build-in sources: /dev/urandom

description - описание источника
expire      - время, после которого нужно будет обновить данные из источника
type        - тип определяем способ получения данных [sourceType, sourceFormat, cacheFormat]
url         - 
datasets    - результирующие наборы данных

mongo_test:
  description: Тестовая база
  expire: 1d
  type: [mongo, cursor, json]
  url: mongodb://172.17.0.2:27017
  datasets:
    star_size: [space, star, size]
    star_type: [space, star, type]
    planet_age: [space, planet, age]

csv_test:
  description: Zip-codes штатов США на состояние 2014 года
  expire: never
  type: [file, csv, json]
  url: https://www.irs.gov/pub/irs-soi/14zpallagi.csv
  datasets:
    users: users

page_test:
  description: Котировки с Яндекса за 10 последние дней
  expire: 1m
  type: [file, html, json]
  url: https://news.yandex.ru/quotes/1.html
  datasets:
    price: td.quote__value
    name: td.quote__change

json_test:
  description: Тестовые данные для MongoDB
  expire: never
  type: [file, json, json]
  url: http://media.mongodb.org/zips.json
  datasets:
    price: td.quote__value
    name: td.quote__change

# https://www.vesselfinder.com/vesselsonmap?bbox=31.538128903937277%2C-29.54691472643175%2C32.06890588147635%2C-29.05770662045262&zoom=11&mmsi=0&show_names=0&ref=60064.800782705286&pv=6
# https://www.vesselfinder.com/clickinfo?mmsi=258926000&rn=81278.6241013219&_=1486097876902